# Common startup for all Makefiles
# This file is automatically generated

VERSION		= 1.3.6
machine		= arm64
os		= Darwin
prefix		= /usr/local
CC		= gcc
CFLAGS = -O2 -Wno-deprecated-non-prototype
stkdir		= $(prefix)/lib/stk
libdir 		= $(stkdir)/$(VERSION)
execdir		= $(prefix)/bin/arch/$(os)/$(machine)
confdir		= $(execdir)/Config
ardir		= $(execdir)/Libs
incdir		= $(prefix)/include
mandir 		= $(prefix)/man
bindir 		= $(prefix)/bin
sharedir	= $(prefix)/share/stk
